---
title: "Referencias"
format:
  html:
    theme: 
      - cosmo
    css: 
      - styles.css
      - references-style.css
---
:::{#Crystal2000}
Crystal, D. (2000). Language death. Cambridge University Press.
:::
:::{#Fasold1984}
Fasold, R. (1984). The sociolinguistics of society. Basil Blackwell. Oxford.
:::
:::{#Ferguson1959}
Ferguson, C. A. (1959). Diglossia. Word, 15(2), 325-340.
:::
:::{#Ferguson1967}
Ferguson, C. A. (1967). On Sociolinguistically Oriented Language Surveys. The Bible Translator, 18(3), 128-132. https://doi.org/10.1177/000608446701800309 (Original work published 1967)
:::
:::{#Fishman1965}
Fishman, J. (1965). «Who Speaks What Language to Whom and When?» en La Linguistique, 1(2), 67-88. (consultado en línea desde http://www.jstor.org/stable/30248773 el 9 de abril de 2021)
:::
:::{#Fishman1972}
Fishman, J.A.:(1972). «Domains and the relationship between micro- and macro- sociolinguistics», en J.J. Gumperz & D. Hymes (eds.), Directions in Sociolinguistics: The Ethnography of Communication, Holt, Rinehart & Winston, pp. 435–453.
:::
:::{#Fishman1991}
Fishman, J. A. (1991). Reversing language shift: Theoretical and empirical foundations of assistance to threatened languages. Multilingual Matters.
:::
:::{#Fishman2001}
Fishman, J. A. (2001). Can threatened languages be saved? Reversing language shift, revisited: A 21st century perspective. Multilingual Matters.
:::
:::{#Garner2005}
Garner, M. (2005). Language ecology as linguistic theory. *Kajian Linguistik dan Sastra*, Vol. 17, No. 33. 91 - 101
:::
:::{#Gumperz1962}
Gumperz, J. J. (1962). Types of Linguistic Communities. Anthropological Linguistics, 4(1), 28–40. http://www.jstor.org/stable/30022343
:::
:::{#Hamel1993}
Hamel, R. E. (1993). Políticas y planificación del lenguaje: una introducción. Iztapalapa, 29, 5-39.
:::
:::{#Haugen1959}
Haugen, E. (1959). Planning for a standard language in modern Norway en *Anthropological linguistics*, 35(1/4), 109–123. http://www.jstor.org/stable/30028247
:::
:::{#Haugen1966}
Haugen, E. (1966). Dialect, language, nation. American Anthropologist, 68(4), 922–935. https://www.jstor.org/stable/670407
:::
:::{#Haugen1972}
Haugen, E. (1972) The Ecology of Language. Standford. CA. Stanford University Press.
:::
:::{#Haugen1982}
Haugen, E. (1982). The Implementation of Corpus Planning: Theory and Practice. In Progress in Language Planning (pp. 269–290). DE GRUYTER. https://doi.org/10.1515/9783110820584.269
:::
:::{#Heath1972}
Heath, S. B. (1972). La política del lenguaje en México, de la colonia a la nación. México, D.F.: Instituto Nacional Indigenista.
:::
:::{#Hechter2000}
Hechter, M. (2000). Containing nationalism. Oxford University Press.
:::
:::{#Hymes1972}
Hymes, D. (1972). «On communicative competence» en Sociolinguistics. pp. 269-293.
:::
:::{#JernuddNekvapil2012}
Jernudd, B., & Nekvapil, J. (2012). History of the field: A sketch. The Cambridge handbook of language policy, 16-36.
:::
:::{#Kloss1966}
Kloss, H. (1966), Types of Multilingual Communities: A Discussion of Ten Variables. Sociological Inquiry, 36: 135-145. https://doi.org/10.1111/j.1475-682X.1966.tb00621.x
:::
:::{#Kloss1969}
Kloss, Heinz. 1969. Research possibilities on group bilingualism: A report. Quebec: International Center for research on Bilingualism.
:::
:::{#Krauss1992}
Krauss, M. (1992) The World’s Languages in Crisis. Language, 68, 4-10. https://doi.org/10.1353/lan.1992.0075
:::
:::{#Krauss1998}
Krauss, M. (1998). The condition of Native North American languages: the need for realistic assessment and action. *International Journal of Sociology of Language.  132  (1998),  pp.  9-21
:::
:::{#Kymlicka2001}
Kymlicka, W. (2001) *Politics in the Vernacular Nationalism, Multiculturalism, and Citizenship*. Oxford.
:::
:::{#KymlickaPatten2003}
Kymlicka, W. y Patten, A. (2003): *Language Rights and Political Theory*, Oxford.
:::
:::{#Labrie1996}
Labrie, N. (1996). La politique linguistique. En H. Goebl, P. H. Nelde, Z. Starý & W. Wölck (Eds.), *Contact Linguistics: An International Handbook of Contemporary Research* (Vol. 1, pp. 826-834). Berlin: Walter de Gruyter.
:::
::: {#Nekvapil2006}
Nekvapil, J. (2006). From language planning to language management. Sociolinguistica: International Yearbook of European Sociolinguistics, 20, pp. 92-104.
:::
::: {#Neustupny2006}
Neustupny,J.V.(2006): Sociolinguistic aspects of social modernization. In U.Ammon,N. Dittmar,K.J.
Mattheier and P. Trudgill (eds), Sociolinguistics. An International Handbook of the Science of Language and Society. Berlin/New York:Walter de Gruyter,2209-2223
:::
:::{#PerezTejada2024}
Pérez Tejada Ladrón de Guevara, J. P. (2024). La alfabetización en lengua materna en México (1939-1959): Las Políticas del lenguaje durante los primeros años del indigenismo mexicano [Tesis de licenciatura, Escuela Nacional de Antropología e Historia].
:::
:::{#Ricento2000}
Ricento, T. (2000). Historical and theoretical perspectives in language policy and planning. Journal of Sociolinguistics, 4, 196-213.
:::
:::{#Ricento2006}
Ricento, T. (2006). Language policy: Theory and practice—An introduction. En T. Ricento (Ed.), *An Introduction to Language Policy: Theory and Method* (pp. 10-23). Malden, MA: Blackwell.
:::
:::{#Sabatier1986}
Sabatier, P. A. (1986). Top-Down and Bottom-Up Approaches to Implementation Research: a Critical Analysis and Suggested Synthesis. Journal of Public Policy, 6(1), 21–48. doi:10.1017/S0143814X00003846
:::
:::{#Schiffman1996}
Schiffman, H. (1996). Linguistic culture and language policy. Taylor & Francis Group.
:::
:::{#Shohamy2006}
Shohamy, E. (2006). Language policy: Hidden agendas and new approaches. London: Routledge.
:::
::: {#Spolsky2004}
Spolsky, B. (2004). Language policy. Cambridge: Cambridge University Press.
:::
::: {#Spolsky2009}
Spolsky, B. (2009). Language policy and language assessment. New York, NY: Cambridge Univ. Press.
:::
::: {#Spolsky2012}
Spolsky, B. (Ed.). (2012). The Cambridge Handbook of Language Policy (Cambridge Handbooks in Language and Linguistics). Cambridge: Cambridge University Press. doi:10.1017/CBO9780511979026
:::
:::{#Stewart1968}
Stewart, W. A. (1968). A Sociolinguistic Typology for Describing National Multilingualism”, Reading in the Sociology of Language.
:::
:::{#Tauli1968}
Tauli, V. 1968 , Introduction to a Theory of Language Planning , Uppsala (Acta Universitatis Upsaliensis. Studia Philologiae Scandinavicae Upsaliensia 6).
:::
:::{#Tollefson1991}
Tollefson, J. W. (1991). *Planning Language, Planning Inequality: Language Policy in the Community*. Londres/Nueva York: Longman.
:::
:::{#Tollefson2006}
Tollefson, J. W. (2006). Critical theory in language policy. En T. Ricento (Ed.), *An Introduction to Language Policy: Theory and Method* (pp. 42-59). Oxford: Blackwell.
:::
:::{#ThomasonKaufman1988}
Thomason, S. G., & Kaufman, T. (1988). Language contact, creolization, and genetic linguistics. University of California Press.
:::
:::{#VandenbusscheJahrTrudgill2013}
Vandenbussche, W., Jahr, E. H., & Trudgill, P. (2013). Language Ecology for the 21st Century: Linguistic Conflicts and Social Environments. Novus Press. Oslo.
:::
:::{#VanDijk1998}
Van Dijk, T. A. (1998). Ideology: A multidisciplinary approach. Sage Publications.
:::
:::{#WoolardSchieffelin1994}
Woolard, K. A., & Schieffelin, B. B. (1994). Language Ideology. Annual Review of Anthropology, 23, 55–82. http://www.jstor.org/stable/2156006
:::
:::{#Weinreich1953}
Weinreich, U. (1953). Languages in contact: Findings and problems. New York: Linguistic Circle of New York.
:::
:::{#Winford2003}
Winford, D. (2003). An introduction to contact linguistics. Malden, MA: Blackwell Publishing.
:::
:::{#Zimmerman1999}
Zimmerman, K. (1999). Política del lenguaje y planificación para los pueblos amerindios: ensayos de ecología lingüística. Universidad Iberoamericana.
:::
